/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NavItem = {
  _type: 'navItem'
  type: 'link' | 'dropdown'
  link?: Link
  dropdownLabel?: string
  dropdownItems?: Array<
    {
      _key: string
    } & Link
  >
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'small' | 'lead' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'number' | 'bullet'
        markDefs?: Array<{
          linkType?: 'href' | 'page' | 'category' | 'post'
          href?: string
          page?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'page'
          }
          post?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'post'
          }
          category?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'category'
          }
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        _type: 'portableImage'
        _key: string
      }
  >
}

export type CallToAction = {
  _type: 'callToAction'
  heading: string
  text?: string
  buttonText?: string
  link?: Link
}

export type Link = {
  _type: 'link'
  linkType?: 'page' | 'post' | 'category' | 'href'
  label?: string
  openInNewTab?: boolean
  href?: string
  page?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'home'
      }
  post?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'post'
  }
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'category'
  }
}

export type BlockContentBasic = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: 'number' | 'bullet'
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'small' | 'lead' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'number' | 'bullet'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'category' | 'post'
        href?: string
        page?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
        post?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'post'
        }
        category?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'category'
        }
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: 'portableImage'
      _key: string
    }
>

export type Tribe = {
  _id: string
  _type: 'tribe'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  region: 'north' | 'central' | 'south' | 'statewide'
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'imageWithAlt'
  }
  shortDescription: BlockContentBasic
  description: BlockContent
  contactInfo?: {
    address?: string
    city?: string
    state?: string
    zip?: string
    phone?: string
    email?: string
    website?: string
  }
  metadata?: Metadata
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  region: 'north' | 'central' | 'south' | 'statewide'
  serviceType: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'serviceType'
  }
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'imageWithAlt'
  }
  shortDescription: BlockContentBasic
  description: BlockContent
  contactInfo?: {
    address?: string
    city?: string
    state?: string
    zip?: string
    phone?: string
    email?: string
    website?: string
  }
  hours?: {
    days?: string
    open?: string
    close?: string
  }
  metadata?: Metadata
}

export type ServiceType = {
  _id: string
  _type: 'serviceType'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'imageWithAlt'
  }
  order?: number
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  biography?: BlockContentBasic
  twitterId?: string
  linkedinId?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
  metadata?: Metadata
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  postType: 'article' | 'guide' | 'tool'
  title: string
  slug: Slug
  date?: string
  region: 'north' | 'central' | 'south' | 'statewide'
  category: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'category'
  }
  topic: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'topic'
  }
  authors: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  toolFile?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
  externalLink?: string
  excerpt: BlockContentBasic
  body: BlockContent
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'imageWithAlt'
  }
  metadata?: Metadata
}

export type Topic = {
  _id: string
  _type: 'topic'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  parentCategory: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'category'
  }
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'imageWithAlt'
  }
  order?: number
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'imageWithAlt'
  }
  order?: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    metadataBase?: string
    _type: 'image'
  }
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  primaryNav?: Array<
    {
      _key: string
    } & NavItem
  >
  footerNav?: Array<
    {
      _key: string
    } & Link
  >
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  hero?: {
    heading: string
    subheading?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: 'imageWithAlt'
    }
  }
  featuredPosts: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'post'
  }>
  showFeaturedServices?: boolean
  featuredServices?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'service'
  }>
  seo?: Metadata
}

export type Metadata = {
  _type: 'metadata'
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  hideSearchIndex?: boolean
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  asset?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
  }
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
  }
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | NavItem
  | InfoSection
  | CallToAction
  | Link
  | BlockContentBasic
  | BlockContent
  | Tribe
  | Tag
  | Service
  | ServiceType
  | Person
  | Page
  | Post
  | Topic
  | Category
  | Settings
  | Navigation
  | Home
  | Metadata
  | ImageWithAlt
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    metadataBase?: string
    _type: 'image'
  }
} | null
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]{    primaryNav[]{      _key,      _type,      type,      link{          _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }      },      dropdownLabel,      dropdownItems[]{          _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }      }    },    footerNav[]{        _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }    }  }
export type NavigationQueryResult = {
  primaryNav: Array<{
    _key: string
    _type: 'navItem'
    type: 'dropdown' | 'link'
    link: {
      _type: 'link'
      linkType: 'category' | 'href' | 'page' | 'post' | null
      label: string | null
      openInNewTab: boolean | null
      page:
        | {
            name: string
            slug: string
          }
        | {
            name: string | null
            slug: null
          }
        | null
      post: {
        title: string
        slug: string
      } | null
      category: {
        name: string
        description: string | null
        slug: string
        image: {
          alt: string
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          } | null
          metadata: SanityImageMetadata | null
          url: string | null
          extension: string | null
        } | null
      } | null
    } | null
    dropdownLabel: string | null
    dropdownItems: Array<{
      _type: 'link'
      linkType: 'category' | 'href' | 'page' | 'post' | null
      label: string | null
      openInNewTab: boolean | null
      page:
        | {
            name: string
            slug: string
          }
        | {
            name: string | null
            slug: null
          }
        | null
      post: {
        title: string
        slug: string
      } | null
      category: {
        name: string
        description: string | null
        slug: string
        image: {
          alt: string
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          } | null
          metadata: SanityImageMetadata | null
          url: string | null
          extension: string | null
        } | null
      } | null
    }> | null
  }> | null
  footerNav: Array<{
    _type: 'link'
    linkType: 'category' | 'href' | 'page' | 'post' | null
    label: string | null
    openInNewTab: boolean | null
    page:
      | {
          name: string
          slug: string
        }
      | {
          name: string | null
          slug: null
        }
      | null
    post: {
      title: string
      slug: string
    } | null
    category: {
      name: string
      description: string | null
      slug: string
      image: {
        alt: string
        asset: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        } | null
        metadata: SanityImageMetadata | null
        url: string | null
        extension: string | null
      } | null
    } | null
  }> | null
} | null
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    metadata,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {          link {      _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }  },      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  metadata: Metadata | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        heading: string
        text?: string
        buttonText?: string
        link: {
          _type: 'link'
          linkType: 'category' | 'href' | 'page' | 'post' | null
          label: string | null
          openInNewTab: boolean | null
          page:
            | {
                name: string
                slug: string
              }
            | {
                name: string | null
                slug: null
              }
            | null
          post: {
            title: string
            slug: string
          } | null
          category: {
            name: string
            description: string | null
            slug: string
            image: {
              alt: string
              asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              } | null
              metadata: SanityImageMetadata | null
              url: string | null
              extension: string | null
            } | null
          } | null
        } | null
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType: 'category' | 'href' | 'page' | 'post' | null
                href?: string
                page: {
                  name: string
                  slug: string
                } | null
                post: {
                  title: string
                  slug: string
                } | null
                category: {
                  name: string
                  description: string | null
                  slug: string
                  image: {
                    alt: string
                    asset: {
                      _ref: string
                      _type: 'reference'
                      _weak?: boolean
                      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
                    } | null
                    metadata: SanityImageMetadata | null
                    url: string | null
                    extension: string | null
                  } | null
                } | null
                openInNewTab: boolean | null
                _type: 'link'
                _key: string
                label: null
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              }
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt: string
              _type: 'portableImage'
              _key: string
              markDefs: null
            }
        > | null
      }
  > | null
} | null
// Variable: getHomepageQuery
// Query: *[_type == "home"][0]{    hero{      heading,      subheading,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    },    featuredPosts[]->{        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region    },    featuredServices[]->{      ...    },    seo  }
export type GetHomepageQueryResult = {
  hero: {
    heading: string
    subheading: string | null
    image: {
      alt: string
      asset: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      } | null
      metadata: SanityImageMetadata | null
      url: string | null
      extension: string | null
    } | null
  } | null
  featuredPosts: Array<{
    _id: string
    status: 'draft' | 'published'
    postType: 'article' | 'guide' | 'tool'
    slug: string
    title: string
    excerpt: BlockContentBasic
    coverImage: {
      alt: string
      asset: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      } | null
      metadata: SanityImageMetadata | null
      url: string | null
      extension: string | null
    } | null
    date: string
    category: {
      name: string
      slug: string
      description: string | null
    }
    topic: {
      name: string
      slug: string
      description: string | null
    }
    region: 'central' | 'north' | 'south' | 'statewide'
  }>
  featuredServices: Array<{
    _id: string
    _type: 'service'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name: string
    slug: Slug
    region: 'central' | 'north' | 'south' | 'statewide'
    serviceType: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'serviceType'
    }
    coverImage: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: 'imageWithAlt'
    }
    shortDescription: BlockContentBasic
    description: BlockContent
    contactInfo?: {
      address?: string
      city?: string
      state?: string
      zip?: string
      phone?: string
      email?: string
      website?: string
    }
    hours?: {
      days?: string
      open?: string
      close?: string
    }
    metadata?: Metadata
  }> | null
  seo: Metadata | null
} | null
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" || _type == "service" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    "categorySlug": category->slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      categorySlug: null
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      categorySlug: string
      _type: 'post'
      _updatedAt: string
    }
  | {
      slug: string
      categorySlug: null
      _type: 'service'
      _updatedAt: string
    }
>
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region,  body[]{    ...,    markDefs[]{      ...,        _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }    }  },  "headings": body[_type == "block" && style in ["h2", "h3"]]{    _key,    "level": style,    "text": pt::text(@)  },  authors[]->{firstName, lastName, picture},  toolFile{    _type,    asset->{      extension,      mimeType,      originalFilename,      size,      url    },    media  },  externalLink,  metadata  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  postType: 'article' | 'guide' | 'tool'
  slug: string
  title: string
  excerpt: BlockContentBasic
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  date: string
  category: {
    name: string
    slug: string
    description: string | null
  }
  topic: {
    name: string
    slug: string
    description: string | null
  }
  region: 'central' | 'north' | 'south' | 'statewide'
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType: 'category' | 'href' | 'page' | 'post' | null
          href?: string
          page: {
            name: string
            slug: string
          } | null
          post: {
            title: string
            slug: string
          } | null
          category: {
            name: string
            description: string | null
            slug: string
            image: {
              alt: string
              asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              } | null
              metadata: SanityImageMetadata | null
              url: string | null
              extension: string | null
            } | null
          } | null
          openInNewTab: boolean | null
          _type: 'link'
          _key: string
          label: null
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        _type: 'portableImage'
        _key: string
        markDefs: null
      }
  >
  headings: Array<{
    _key: string
    level: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small' | null
    text: string
  }>
  authors: Array<{
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }>
  toolFile: {
    _type: 'file'
    asset: {
      extension: string | null
      mimeType: string | null
      originalFilename: string | null
      size: number | null
      url: string | null
    } | null
    media: unknown | null
  } | null
  externalLink: string | null
  metadata: Metadata | null
}>
// Variable: getPostsByTypeQuery
// Query: *[_type == "post" && postType == $postType] | order(date desc, _updatedAt desc) {        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region,  body[]{    ...,    markDefs[]{      ...,        _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }    }  },  "headings": body[_type == "block" && style in ["h2", "h3"]]{    _key,    "level": style,    "text": pt::text(@)  },  authors[]->{firstName, lastName, picture},  toolFile{    _type,    asset->{      extension,      mimeType,      originalFilename,      size,      url    },    media  },  externalLink,  metadata  }
export type GetPostsByTypeQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  postType: 'article' | 'guide' | 'tool'
  slug: string
  title: string
  excerpt: BlockContentBasic
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  date: string
  category: {
    name: string
    slug: string
    description: string | null
  }
  topic: {
    name: string
    slug: string
    description: string | null
  }
  region: 'central' | 'north' | 'south' | 'statewide'
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType: 'category' | 'href' | 'page' | 'post' | null
          href?: string
          page: {
            name: string
            slug: string
          } | null
          post: {
            title: string
            slug: string
          } | null
          category: {
            name: string
            description: string | null
            slug: string
            image: {
              alt: string
              asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              } | null
              metadata: SanityImageMetadata | null
              url: string | null
              extension: string | null
            } | null
          } | null
          openInNewTab: boolean | null
          _type: 'link'
          _key: string
          label: null
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        _type: 'portableImage'
        _key: string
        markDefs: null
      }
  >
  headings: Array<{
    _key: string
    level: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small' | null
    text: string
  }>
  authors: Array<{
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }>
  toolFile: {
    _type: 'file'
    asset: {
      extension: string | null
      mimeType: string | null
      originalFilename: string | null
      size: number | null
      url: string | null
    } | null
    media: unknown | null
  } | null
  externalLink: string | null
  metadata: Metadata | null
}>
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region,  body[]{    ...,    markDefs[]{      ...,        _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }    }  },  "headings": body[_type == "block" && style in ["h2", "h3"]]{    _key,    "level": style,    "text": pt::text(@)  },  authors[]->{firstName, lastName, picture},  toolFile{    _type,    asset->{      extension,      mimeType,      originalFilename,      size,      url    },    media  },  externalLink,  metadata  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  postType: 'article' | 'guide' | 'tool'
  slug: string
  title: string
  excerpt: BlockContentBasic
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  date: string
  category: {
    name: string
    slug: string
    description: string | null
  }
  topic: {
    name: string
    slug: string
    description: string | null
  }
  region: 'central' | 'north' | 'south' | 'statewide'
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType: 'category' | 'href' | 'page' | 'post' | null
          href?: string
          page: {
            name: string
            slug: string
          } | null
          post: {
            title: string
            slug: string
          } | null
          category: {
            name: string
            description: string | null
            slug: string
            image: {
              alt: string
              asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              } | null
              metadata: SanityImageMetadata | null
              url: string | null
              extension: string | null
            } | null
          } | null
          openInNewTab: boolean | null
          _type: 'link'
          _key: string
          label: null
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        _type: 'portableImage'
        _key: string
        markDefs: null
      }
  >
  headings: Array<{
    _key: string
    level: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small' | null
    text: string
  }>
  authors: Array<{
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }>
  toolFile: {
    _type: 'file'
    asset: {
      extension: string | null
      mimeType: string | null
      originalFilename: string | null
      size: number | null
      url: string | null
    } | null
    media: unknown | null
  } | null
  externalLink: string | null
  metadata: Metadata | null
}>
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region,  body[]{    ...,    markDefs[]{      ...,        _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }    }  },  "headings": body[_type == "block" && style in ["h2", "h3"]]{    _key,    "level": style,    "text": pt::text(@)  },  authors[]->{firstName, lastName, picture},  toolFile{    _type,    asset->{      extension,      mimeType,      originalFilename,      size,      url    },    media  },  externalLink,  metadata  }
export type PostQueryResult = {
  _id: string
  status: 'draft' | 'published'
  postType: 'article' | 'guide' | 'tool'
  slug: string
  title: string
  excerpt: BlockContentBasic
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  date: string
  category: {
    name: string
    slug: string
    description: string | null
  }
  topic: {
    name: string
    slug: string
    description: string | null
  }
  region: 'central' | 'north' | 'south' | 'statewide'
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType: 'category' | 'href' | 'page' | 'post' | null
          href?: string
          page: {
            name: string
            slug: string
          } | null
          post: {
            title: string
            slug: string
          } | null
          category: {
            name: string
            description: string | null
            slug: string
            image: {
              alt: string
              asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              } | null
              metadata: SanityImageMetadata | null
              url: string | null
              extension: string | null
            } | null
          } | null
          openInNewTab: boolean | null
          _type: 'link'
          _key: string
          label: null
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        _type: 'portableImage'
        _key: string
        markDefs: null
      }
  >
  headings: Array<{
    _key: string
    level: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small' | null
    text: string
  }>
  authors: Array<{
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }>
  toolFile: {
    _type: 'file'
    asset: {
      extension: string | null
      mimeType: string | null
      originalFilename: string | null
      size: number | null
      url: string | null
    } | null
    media: unknown | null
  } | null
  externalLink: string | null
  metadata: Metadata | null
} | null
// Variable: getPostQuery
// Query: *[_type == "post" && slug.current == $slug && category->slug.current == $categorySlug][0] {    body[]{      ...,      markDefs[]{        ...,          _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }      }    },        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region,  body[]{    ...,    markDefs[]{      ...,        _type == "link" => {    _type,    linkType,    label,    openInNewTab,    page->{      name,      "slug": slug.current    },    post->{      title,      "slug": slug.current    },    category->{      name,      description,      "slug": slug.current,      image{          alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension      }    }  }    }  },  "headings": body[_type == "block" && style in ["h2", "h3"]]{    _key,    "level": style,    "text": pt::text(@)  },  authors[]->{firstName, lastName, picture},  toolFile{    _type,    asset->{      extension,      mimeType,      originalFilename,      size,      url    },    media  },  externalLink,  metadata  }
export type GetPostQueryResult = {
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType: 'category' | 'href' | 'page' | 'post' | null
          href?: string
          page: {
            name: string
            slug: string
          } | null
          post: {
            title: string
            slug: string
          } | null
          category: {
            name: string
            description: string | null
            slug: string
            image: {
              alt: string
              asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              } | null
              metadata: SanityImageMetadata | null
              url: string | null
              extension: string | null
            } | null
          } | null
          openInNewTab: boolean | null
          _type: 'link'
          _key: string
          label: null
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        _type: 'portableImage'
        _key: string
        markDefs: null
      }
  >
  _id: string
  status: 'draft' | 'published'
  postType: 'article' | 'guide' | 'tool'
  slug: string
  title: string
  excerpt: BlockContentBasic
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  date: string
  category: {
    name: string
    slug: string
    description: string | null
  }
  topic: {
    name: string
    slug: string
    description: string | null
  }
  region: 'central' | 'north' | 'south' | 'statewide'
  headings: Array<{
    _key: string
    level: 'blockquote' | 'h2' | 'h3' | 'h4' | 'lead' | 'normal' | 'small' | null
    text: string
  }>
  authors: Array<{
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }>
  toolFile: {
    _type: 'file'
    asset: {
      extension: string | null
      mimeType: string | null
      originalFilename: string | null
      size: number | null
      url: string | null
    } | null
    media: unknown | null
  } | null
  externalLink: string | null
  metadata: Metadata | null
} | null
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>
// Variable: allCategoriesQuery
// Query: *[_type == "category" && defined(slug.current)] | order(order asc) {      _id,  name,  "slug": slug.current,  description,  image{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  order  }
export type AllCategoriesQueryResult = Array<{
  _id: string
  name: string
  slug: string
  description: string | null
  image: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  order: number | null
}>
// Variable: getCategoryQuery
// Query: *[_type == 'category' && slug.current == $slug][0]{      _id,  name,  "slug": slug.current,  description,  image{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  order  }
export type GetCategoryQueryResult = {
  _id: string
  name: string
  slug: string
  description: string | null
  image: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  order: number | null
} | null
// Variable: getCategoryWithAllPostsQuery
// Query: *[_type == 'category' && slug.current == $slug][0]{      _id,  name,  "slug": slug.current,  description,  image{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  order,    "posts": *[_type == "post" && category._ref == ^._id] | order(date desc, _updatedAt desc) {        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region    },    "availableTopics": array::unique(*[_type == "post" && category._ref == ^._id && defined(topic)].topic->{      name,      "slug": slug.current    })  }
export type GetCategoryWithAllPostsQueryResult = {
  _id: string
  name: string
  slug: string
  description: string | null
  image: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  order: number | null
  posts: Array<{
    _id: string
    status: 'draft' | 'published'
    postType: 'article' | 'guide' | 'tool'
    slug: string
    title: string
    excerpt: BlockContentBasic
    coverImage: {
      alt: string
      asset: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      } | null
      metadata: SanityImageMetadata | null
      url: string | null
      extension: string | null
    } | null
    date: string
    category: {
      name: string
      slug: string
      description: string | null
    }
    topic: {
      name: string
      slug: string
      description: string | null
    }
    region: 'central' | 'north' | 'south' | 'statewide'
  }>
  availableTopics: Array<{
    name: string
    slug: string
  }>
} | null
// Variable: allTopicsQuery
// Query: *[_type == "topic" && defined(slug.current)] | order(order asc) {      _id,  name,  "slug": slug.current,  description,  image{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  order  }
export type AllTopicsQueryResult = Array<{
  _id: string
  name: string
  slug: string
  description: string | null
  image: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  order: number | null
}>
// Variable: getTopicQuery
// Query: *[_type == 'topic' && slug.current == $slug][0]{      _id,  name,  "slug": slug.current,  description,  image{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  order  }
export type GetTopicQueryResult = {
  _id: string
  name: string
  slug: string
  description: string | null
  image: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  order: number | null
} | null
// Variable: getTopicWithAllPostsQuery
// Query: *[_type == 'topic' && slug.current == $slug][0]{      _id,  name,  "slug": slug.current,  description,  image{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  order,    "posts": *[_type == "post" && topic._ref == ^._id] | order(date desc, _updatedAt desc) {        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  postType,  "slug": slug.current,  "title": coalesce(title, "Untitled"),  excerpt,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  "date": coalesce(date, _updatedAt),  category->{name, "slug": slug.current, description},  topic->{name, "slug": slug.current, description},  region    },    "availableTopics": array::unique(*[_type == "post" && category._ref == ^._id && defined(topic)].topic->{      name,      "slug": slug.current    })  }
export type GetTopicWithAllPostsQueryResult = {
  _id: string
  name: string
  slug: string
  description: string | null
  image: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  } | null
  order: number | null
  posts: Array<{
    _id: string
    status: 'draft' | 'published'
    postType: 'article' | 'guide' | 'tool'
    slug: string
    title: string
    excerpt: BlockContentBasic
    coverImage: {
      alt: string
      asset: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      } | null
      metadata: SanityImageMetadata | null
      url: string | null
      extension: string | null
    } | null
    date: string
    category: {
      name: string
      slug: string
      description: string | null
    }
    topic: {
      name: string
      slug: string
      description: string | null
    }
    region: 'central' | 'north' | 'south' | 'statewide'
  }>
  availableTopics: Array<{
    name: string
    slug: string
  }>
} | null
// Variable: allServicesQuery
// Query: *[_type == "service" && defined(slug.current)] | order(name asc) {      _id,  _type,  _updatedAt,  contactInfo,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  name,  region,  serviceType->{    name,    "slug": slug.current  },  "slug": slug.current,  shortDescription  }
export type AllServicesQueryResult = Array<{
  _id: string
  _type: 'service'
  _updatedAt: string
  contactInfo: {
    address?: string
    city?: string
    state?: string
    zip?: string
    phone?: string
    email?: string
    website?: string
  } | null
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  }
  name: string
  region: 'central' | 'north' | 'south' | 'statewide'
  serviceType: {
    name: string
    slug: string
  }
  slug: string
  shortDescription: BlockContentBasic
}>
// Variable: getServiceQuery
// Query: *[_type == "service" && slug.current == $slug][0] {        _id,  _type,  _updatedAt,  contactInfo,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  name,  region,  serviceType->{    name,    "slug": slug.current  },  "slug": slug.current,  shortDescription,  description,  hours,  metadata  }
export type GetServiceQueryResult = {
  _id: string
  _type: 'service'
  _updatedAt: string
  contactInfo: {
    address?: string
    city?: string
    state?: string
    zip?: string
    phone?: string
    email?: string
    website?: string
  } | null
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  }
  name: string
  region: 'central' | 'north' | 'south' | 'statewide'
  serviceType: {
    name: string
    slug: string
  }
  slug: string
  shortDescription: BlockContentBasic
  description: BlockContent
  hours: {
    days?: string
    open?: string
    close?: string
  } | null
  metadata: Metadata | null
} | null
// Variable: allTribesQuery
// Query: *[_type == "tribe" && defined(slug.current)] | order(name asc) {      _id,  _type,  _updatedAt,  contactInfo,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  name,  region,  "slug": slug.current,  shortDescription  }
export type AllTribesQueryResult = Array<{
  _id: string
  _type: 'tribe'
  _updatedAt: string
  contactInfo: {
    address?: string
    city?: string
    state?: string
    zip?: string
    phone?: string
    email?: string
    website?: string
  } | null
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  }
  name: string
  region: 'central' | 'north' | 'south' | 'statewide'
  slug: string
  shortDescription: BlockContentBasic
}>
// Variable: getTribeQuery
// Query: *[_type == "tribe" && slug.current == $slug][0] {        _id,  _type,  _updatedAt,  contactInfo,  coverImage{      alt,  asset,  "metadata": asset->metadata,  "url": asset->url,  "extension": asset->extension  },  name,  region,  "slug": slug.current,  shortDescription,  description,  metadata  }
export type GetTribeQueryResult = {
  _id: string
  _type: 'tribe'
  _updatedAt: string
  contactInfo: {
    address?: string
    city?: string
    state?: string
    zip?: string
    phone?: string
    email?: string
    website?: string
  } | null
  coverImage: {
    alt: string
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    metadata: SanityImageMetadata | null
    url: string | null
    extension: string | null
  }
  name: string
  region: 'central' | 'north' | 'south' | 'statewide'
  slug: string
  shortDescription: BlockContentBasic
  description: BlockContent
  metadata: Metadata | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == "navigation"][0]{\n    primaryNav[]{\n      _key,\n      _type,\n      type,\n      link{\n        \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n      },\n      dropdownLabel,\n      dropdownItems[]{\n        \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n      }\n    },\n    footerNav[]{\n      \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n    }\n  }\n': NavigationQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    metadata,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        \n  link {\n    \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n  }\n,\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "home"][0]{\n    hero{\n      heading,\n      subheading,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    },\n    featuredPosts[]->{\n      \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n\n    },\n    featuredServices[]->{\n      ...\n    },\n    seo\n  }\n': GetHomepageQueryResult
    '\n  *[_type == "page" || _type == "post" || _type == "service" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    "categorySlug": category->slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n,\n  body[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n    }\n  },\n  "headings": body[_type == "block" && style in ["h2", "h3"]]{\n    _key,\n    "level": style,\n    "text": pt::text(@)\n  },\n  authors[]->{firstName, lastName, picture},\n  toolFile{\n    _type,\n    asset->{\n      extension,\n      mimeType,\n      originalFilename,\n      size,\n      url\n    },\n    media\n  },\n  externalLink,\n  metadata\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && postType == $postType] | order(date desc, _updatedAt desc) {\n    \n  \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n,\n  body[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n    }\n  },\n  "headings": body[_type == "block" && style in ["h2", "h3"]]{\n    _key,\n    "level": style,\n    "text": pt::text(@)\n  },\n  authors[]->{firstName, lastName, picture},\n  toolFile{\n    _type,\n    asset->{\n      extension,\n      mimeType,\n      originalFilename,\n      size,\n      url\n    },\n    media\n  },\n  externalLink,\n  metadata\n\n  }\n': GetPostsByTypeQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n,\n  body[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n    }\n  },\n  "headings": body[_type == "block" && style in ["h2", "h3"]]{\n    _key,\n    "level": style,\n    "text": pt::text(@)\n  },\n  authors[]->{firstName, lastName, picture},\n  toolFile{\n    _type,\n    asset->{\n      extension,\n      mimeType,\n      originalFilename,\n      size,\n      url\n    },\n    media\n  },\n  externalLink,\n  metadata\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    \n  \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n,\n  body[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n    }\n  },\n  "headings": body[_type == "block" && style in ["h2", "h3"]]{\n    _key,\n    "level": style,\n    "text": pt::text(@)\n  },\n  authors[]->{firstName, lastName, picture},\n  toolFile{\n    _type,\n    asset->{\n      extension,\n      mimeType,\n      originalFilename,\n      size,\n      url\n    },\n    media\n  },\n  externalLink,\n  metadata\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && slug.current == $slug && category->slug.current == $categorySlug][0] {\n    body[]{\n      ...,\n      markDefs[]{\n        ...,\n        \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n      }\n    },\n    \n  \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n,\n  body[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    _type,\n    linkType,\n    label,\n    openInNewTab,\n    page->{\n      name,\n      "slug": slug.current\n    },\n    post->{\n      title,\n      "slug": slug.current\n    },\n    category->{\n      name,\n      description,\n      "slug": slug.current,\n      image{\n        \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n      }\n    }\n  }\n\n    }\n  },\n  "headings": body[_type == "block" && style in ["h2", "h3"]]{\n    _key,\n    "level": style,\n    "text": pt::text(@)\n  },\n  authors[]->{firstName, lastName, picture},\n  toolFile{\n    _type,\n    asset->{\n      extension,\n      mimeType,\n      originalFilename,\n      size,\n      url\n    },\n    media\n  },\n  externalLink,\n  metadata\n\n  }\n': GetPostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "category" && defined(slug.current)] | order(order asc) {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  order\n\n  }\n': AllCategoriesQueryResult
    '\n  *[_type == \'category\' && slug.current == $slug][0]{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  order\n\n  }\n': GetCategoryQueryResult
    '\n  *[_type == \'category\' && slug.current == $slug][0]{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  order\n,\n    "posts": *[_type == "post" && category._ref == ^._id] | order(date desc, _updatedAt desc) {\n      \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n\n    },\n    "availableTopics": array::unique(*[_type == "post" && category._ref == ^._id && defined(topic)].topic->{\n      name,\n      "slug": slug.current\n    })\n  }\n': GetCategoryWithAllPostsQueryResult
    '\n  *[_type == "topic" && defined(slug.current)] | order(order asc) {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  order\n\n  }\n': AllTopicsQueryResult
    '\n  *[_type == \'topic\' && slug.current == $slug][0]{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  order\n\n  }\n': GetTopicQueryResult
    '\n  *[_type == \'topic\' && slug.current == $slug][0]{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  order\n,\n    "posts": *[_type == "post" && topic._ref == ^._id] | order(date desc, _updatedAt desc) {\n      \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  postType,\n  "slug": slug.current,\n  "title": coalesce(title, "Untitled"),\n  excerpt,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  "date": coalesce(date, _updatedAt),\n  category->{name, "slug": slug.current, description},\n  topic->{name, "slug": slug.current, description},\n  region\n\n    },\n    "availableTopics": array::unique(*[_type == "post" && category._ref == ^._id && defined(topic)].topic->{\n      name,\n      "slug": slug.current\n    })\n  }\n': GetTopicWithAllPostsQueryResult
    '\n  *[_type == "service" && defined(slug.current)] | order(name asc) {\n    \n  _id,\n  _type,\n  _updatedAt,\n  contactInfo,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  name,\n  region,\n  serviceType->{\n    name,\n    "slug": slug.current\n  },\n  "slug": slug.current,\n  shortDescription\n\n  }\n': AllServicesQueryResult
    '\n  *[_type == "service" && slug.current == $slug][0] {\n    \n  \n  _id,\n  _type,\n  _updatedAt,\n  contactInfo,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  name,\n  region,\n  serviceType->{\n    name,\n    "slug": slug.current\n  },\n  "slug": slug.current,\n  shortDescription\n,\n  description,\n  hours,\n  metadata\n\n  }\n': GetServiceQueryResult
    '\n  *[_type == "tribe" && defined(slug.current)] | order(name asc) {\n    \n  _id,\n  _type,\n  _updatedAt,\n  contactInfo,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  name,\n  region,\n  "slug": slug.current,\n  shortDescription\n\n  }\n': AllTribesQueryResult
    '\n  *[_type == "tribe" && slug.current == $slug][0] {\n    \n  \n  _id,\n  _type,\n  _updatedAt,\n  contactInfo,\n  coverImage{\n    \n  alt,\n  asset,\n  "metadata": asset->metadata,\n  "url": asset->url,\n  "extension": asset->extension\n\n  },\n  name,\n  region,\n  "slug": slug.current,\n  shortDescription\n,\n  description,\n  metadata\n\n  }\n': GetTribeQueryResult
  }
}
